// <auto-generated />
using System;
using KuCoinFuturesReporter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KuCoinFuturesReporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KuCoinFuturesReporter.Models.ClosedPosition", b =>
                {
                    b.Property<string>("CloseId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ClosePrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FundingFee")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal?>("Leverage")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("MarginMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("OpenPrice")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Pnl")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<string>("PositionSide")
                        .HasColumnType("text");

                    b.Property<decimal?>("RealisedGrossCost")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<decimal?>("Roe")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("SettleCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TelegramSent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("TelegramSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TradeFee")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CloseId");

                    b.HasIndex("CloseTime");

                    b.HasIndex("TelegramSent");

                    b.ToTable("ClosedPositions");
                });

            modelBuilder.Entity("KuCoinFuturesReporter.Models.SyncState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastCloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
